name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Install .NET format tool
      run: dotnet tool install -g dotnet-format

    - name: Check code formatting
      run: dotnet-format --check --verbosity diagnostic

    - name: Analyze with Roslyn analyzers
      run: dotnet build --configuration Release --no-restore /p:RunAnalyzers=true

    - name: Run security audit
      run: |
        dotnet list package --vulnerable --include-prerelease
        if [ $? -ne 0 ]; then
          echo "Vulnerable packages found. Please update dependencies."
          exit 1
        fi

    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-analysis-results
        path: |
          **/bin/**/*.json
          **/obj/**/*.json
        retention-days: 7